- name: Setup Docker and Nginx
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Create index.html on the server
      copy:
        content: "<h1>Zeotap Deployment Successful!</h1>"
        dest: /home/ubuntu/index.html
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Run Nginx Container
      community.docker.docker_container:
        name: zeotap-web
        image: nginx:alpine
        ports:
          - "80:80"
        volumes:
          - /home/ubuntu/index.html:/usr/share/nginx/html/index.html
